### ISSUE TITLE
Erreur production PDF dans le cas où un étudiant n'a pas de first_name

### ISSUE THREAD

**Issue by basmot** [uclouvain/osis-common#174]
Traceback (most recent call last):
  File "/home/osis/VENV/lib/python3.4/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/osis/VENV/lib/python3.4/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/osis/VENV/lib/python3.4/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/osis/VENV/lib/python3.4/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/osis/VENV/lib/python3.4/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/osis/www/html/osis_backend/assessments/views/score_encoding.py", line 410, in notes_printing
    return paper_sheet.print_notes(sheet_data)
  File "/home/osis/www/html/osis_backend/osis_common/document/paper_sheet.py", line 55, in print_notes
    return build_response(data)
  File "/home/osis/www/html/osis_backend/osis_common/document/paper_sheet.py", line 114, in build_response
    pdf = build_pdf(data)
  File "/home/osis/www/html/osis_backend/osis_common/document/paper_sheet.py", line 126, in build_pdf
    content = _data_to_pdf_content(data)
  File "/home/osis/www/html/osis_backend/osis_common/document/paper_sheet.py", line 178, in _data_to_pdf_content
    content.extend(_build_page_content(enrollments_by_pdf_page, learn_unit_year, nb_students, program, styles,justification_legend))
  File "/home/osis/www/html/osis_backend/osis_common/document/paper_sheet.py", line 190, in _build_page_content
    page_content.append(_build_exam_enrollments_table(enrollments_by_pdf_page, styles))
  File "/home/osis/www/html/osis_backend/osis_common/document/paper_sheet.py", line 205, in _build_exam_enrollments_table
    Paragraph(enrollment["first_name"], styles['Normal']),
  File "/home/osis/VENV/lib/python3.4/site-packages/reportlab/platypus/paragraph.py", line 1042, in __init__
    self._setup(text, style, bulletText or getattr(style,'bulletText',None), frags, cleanBlockQuotedText)
  File "/home/osis/VENV/lib/python3.4/site-packages/reportlab/platypus/paragraph.py", line 1061, in _setup
    text = cleaner(text)
  File "/home/osis/VENV/lib/python3.4/site-packages/reportlab/platypus/paragraph.py", line 100, in cleanBlockQuotedText
    L=list(filter(truth,list(map(_lineClean, split(text, '\n')))))
  File "/home/osis/VENV/lib/python3.4/site-packages/reportlab/platypus/paragraph.py", line 65, in split
    return [uword for uword in (_wsc_re_split(text) if delim is None and u'\xa0' in text else text.split(delim))]

**Comment by albrugnetti** [comment]
@thuyhanghoang Je viens de faire un test et c'est Ok chez moi. Peux-tu valider? Merci

**Comment by albrugnetti** [comment]
@htmfilho  @basmot  Est-il possible de mettre à jour la référence de osis-common dans osis-portal ? Merci

**Comment by htmfilho** [comment]
C'est fait.
