### ISSUE TITLE
Déplacer les tests dans le dossier de tests et vérifier les tests de tri des fichiers .po

### ISSUE THREAD

**Issue by glamarca** [uclouvain/osis-common#26]
Les tests pour les méthodes de tri des fichiers .po sont dans le dossier scripts, et devraient être dans le dossier tests.

Verifier également le bon fonctionnement des tests:
si python3 manage.py test =>
E
RROR: osis_common.scripts.test_sort_po_files (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python3.4/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib64/python3.4/unittest/case.py", line 615, in run
    testMethod()
  File "/usr/lib64/python3.4/unittest/loader.py", line 32, in testFailure
    raise exception
ImportError: Failed to import test module: osis_common.scripts.test_sort_po_files
Traceback (most recent call last):
  File "/usr/lib64/python3.4/unittest/loader.py", line 312, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib64/python3.4/unittest/loader.py", line 290, in _get_module_from_name
    __import__(name)
  File "/home/glamarca/UCL/OSIS/osis-portal/osis_common/scripts/test_sort_po_files.py", line 29, in <module>
    import scripts.sort_po_files as sort_po_files
ImportError: No module named 'scripts'

**Comment by glamarca** [comment]
@edd19 
Les tests ne fonctionnent pas : 
FAIL: test1 (osis_common.tests.test_sort_po_files.SortPoCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/Info/UCL/OSIS/osis-portal-project/osis-portal/osis_common/tests/test_sort_po_files.py", line 50, in test1
    self.assertEqual(string_actual, string_expected)
AssertionError: '# SO[600 chars]\n"\n\nmsgid "academic_year"\nmsgstr "Academic[24003 chars]s"\n' != '# SO[600 chars]\n"\nmsgid\t "academic_year"\nmsgstr\t "Academ[25299 chars]\n\n'
Diff is 53205 characters long. Set self.maxDiff to None to see it.

**Comment by glamarca** [comment]
Test OK
